### ISSUE TITLE
Error installing into Insomnia 2022.7.5

### ISSUE THREAD

**Issue by solpyro** [glconti/insomnia-plugin-azure-keyvault-secrets#2] opened 2023-02-06 08:28 UTC
When trying to install from the plugin hub, Insomnia prompts me to install or cancel, but I always get the 'Failed to install plugin' message with an empty stacktrace. 

If I use the Insomnia plugins interface, I still don't get the plugin installed. Instead I get this stacktrace:

```
Error: Error invoking remote method 'installPlugin': Error: Yarn error {"type":"warning","data":"package.json: No license field"}
    at a.invoke (node:electron/js2c/renderer_init:2:7610)
    at async onSubmit (file:///C:/Users/XXXXXXXX/AppData/Local/insomnia/app-2022.7.5/resources/app.asar/index.aff207ac.js:178:488)
```

Investigating the repo, it seems you do have this field, and it is populated, so I don't know what yarn's talking about. Have you heard of anyone else encountering this issue or any idea how to resolve it? 

I haven't had a any joy trying to manually install the plugin through CLI & NPM. When I try the CLI says installation succeeds, but the plugin folder doesn't appear in the plugins folder, or in the Insomnia application.

**Comment by glconti** [comment] 2023-02-14 07:52
I am sorry but I couldn't reproduce the issue in any way, it always works to install the plugin, at least for me.
As a disclaimer, I am a beginner in Node development, so keep this in mind!

Here a list of things you can maybe try:
- install any other plugin, to me it seems there could be an issue with the tooling?
- rollback to a previous version of Insomnia and see how it goes
- ask in the [Insomnia Slack channel](https://chat.insomnia.rest/), they are very active and respond very quickly.

And please let me know if there's anything I have to change in the plugin to make it work for you.
For the moment, I will close the issue as I can't reproduce it.

**Closed as completed by glconti** 2023-02-14 07:52 UTC

**Comment by solpyro** [comment] 2023-02-24 08:08
Thanks, I wasn't aware of the Insomnia slack channel. I am able to manually install the plugin by downloading this repo to my plugins folder, so we'll see how that goes.

I'm hoping your plugin will solve some security concerns we have about keeping our api secrets in a local file (no doubt the same concerns that led you to create the plugin :D ) so thanks for actually building this in the first place!

**Comment by tychiadet** [comment] 2024-04-27 06:09
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
ducthinhdeveloper, @ziwon, @AppServiceProvider, @philippatterson, @Jam-all, @dshulman, @He-Jia-Cheng, @svidovich-reach, @austinfennacy, @LambertW, @garcia786, @rpfernandezjr, @johniwasz, @CaseyIPS, @putraxor, @recursionbane, @mascor, @milavdabgar, @gamaged, @CHADHUVULA, @Darkity, @BSalita, @irrationomical, @rusthat, @leovujanic, @nenadg, @DaxxTrias, @msitt, @frozenYu, @godmode2k, @marianzange, @HalidCisse, @dwaynedrexler, @Svisstack, @jinghongbo, @jhill-cmd, @Voldemort373, @tux-00, @dendisuhubdy, @TornikeMzhavia, @tomkren, @dmitriz, @gautomdas, @koko-bap, @joodies, @samael65535, @darcyalcantara, @geraybos, @fmucar, @rushcat
